config/routes.rb
Rails.application.routes.default_url_options[:host] = 'https://localhost:3000'
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "links#index"
  resources :links, only: [:index]
  get '/s/:slug', to: 'links#show', as: :short
  get '/redirect/:slug', to: 'redirect#show', as: :redirect
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/link.rb
class Link < ApplicationRecord

  before_validation :generate_slug

  validates_presence_of :url
  validates :url, format: URI::regexp(%w[http https])
  validates_uniqueness_of :slug
  validates_length_of :url, within: 3..255, on: :create, message: 'URL too long'
  validates_length_of :slug, within: 3..255, on: :create, message: 'Slug too long'

  def short
    Rails.application.routes.url_helpers.short_url(slug: self.slug)
  end

  def generate_slug
    self.slug = SecureRandom.uuid[0..5] if self.slug.nil? || self.slug.empty?
    true
  end

  def self.shorten(url, slug = '')
    link = Link.where(url: url, slug: slug).first
    return link.short if link

    # create a new
    link = Link.new(url: url, slug: slug)
    return link.short if link.save

    # if slug is taken, try to add random characters
    Link.shorten(url, slug + SecureRandom.uuid[0..2])
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/links_controller.rb
class LinksController < ApplicationController

  def index
    @links = Link.all
  end

  def show
    @link = Link.find_by_slug(params[:slug])
    render 'error/404', status: 404 if @link.nil?
  end
end

app/controllers/redirect_controller.rb
class RedirectController < ApplicationController

  def show
    url = params[:url]
    render 'error/404', status: 404 if url.nil?
    redirect_to url, allow_other_host: true
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShortUrlApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/links/index.html.erb
<h1>Links</h1>
<% @links.each do |link| %>
  <li><%= link_to(link.slug, short_path(slug: link.slug)) %></li>
<% end %>

app/views/links/show.html.erb
<h1>Preview of short url / <%= @link.short %></h1>

This short url redirects to: <%= @link.url %>

<%= link_to("Proceed to this site", redirect_path(url: @link.url)) %>